#!/bin/bash

# Create a virtual machine with docker-machine using the virtualbox
# driver, and named Char

# Создайте виртуальную машину с помощью docker-machine, используя
# драйвер virtualbox, и с именем Char

docker-machine create --driver virtualbox Char

# Будет выполняться довольно долго, т.к. потребует первичной загрузки ISO-образа Boot2Docker