#!/bin/bash

# Define the variables needed by your virtual machine Char in the general env of your
# terminal, so that you can run the docker ps command without errors. You have to
# fix all four environment variables with one command, and you are not allowed to
# use your shell’s builtin to set these variables by hand.

# Определите переменные, необходимые вашей виртуальной машине Char, в общем
# окружении (env) вашего терминала, чтобы вы могли выполнить команду docker ps
# без ошибок. Вы должны исправить все четыре переменные среды с помощью одной
# команды, и вам не разрешено использовать встроенную функцию вашей оболочки
# для установки этих переменных вручную.

eval $(docker-machine env Char)